### PR TITLE
Clear up some confusion about auto skip

### PR DESCRIPTION
**Pull request by AbandonedCart**
~~Adding official clients with no button to defaults and~~ Making the relation between menu items a little more intuitive and clearing up some misleading hint text.

### CODE REVIEW

**Comment by jumoog** [comment]
https://github.com/jellyfin/Swiftfin/blob/9ea989c5131acd305344f0bd859c652f5f674eea/Shared/Extensions/UIDevice.swift#L30 i think the name depends on the device?

**Comment by AbandonedCart** [comment]
I can't confirm iPhone, but I can confirm the iPad one has no button.

**Comment by AbandonedCart** [comment]
If things aren’t confusing enough, maybe a reflex would be good (ie. starts with)

**Comment by AbandonedCart** [comment]
In theory, now auto skip settings are universal and the client list only applies to the button.

**Comment by AbandonedCart** [comment]
Thanks for catching that @rlauuzo

**Comment by AbandonedCart** [comment]
- Auto skip has priority over button and client list
    - Auto can be disabled individually on client
- Client list has priority over button
- At least the button or auto must be enabled to do anything

This is the expected functionality. Any scenarios I missed?

**Comment by jumoog** [comment]
good idea

**Comment by dredstone1** [comment]
I think that it would be better to also change the naming "automatically skip intros" into something like always automatically skip intros, or something like that.
The same goes for credits

**Comment by AbandonedCart** [comment]
Wouldn’t that require changing the button to “Sometimes shows the button” then?

**Comment by dredstone1** [comment]
> Wouldn’t that require changing the button to “Sometimes shows the button” then?

ok that's right, i'm sorry, i misunderstood the changes.
but still the current naming is wrong.
what about "enable auto skip for all clients"?
and the description is a bit confusing.

**Comment by AbandonedCart** [comment]
the current naming is wrong. what about "enable auto skip for all clients"? and the description is a bit confusing.

How so? This PR restores how the checkboxes originally worked and makes the client list an addendum to the button.

**Comment by dredstone1** [comment]
The main thing is that, what is the different between the autoskip and the client list?

**Comment by AbandonedCart** [comment]
The checkbox allows you, as the user, to select it and walk away. One setting. No searching or thinking.

But if all you want is a button, you again only have to make one selection.

The client list overrides a client or number of clients that otherwise have a button. This takes things a step further into configuration because you wanted to make some exceptions.

The idea here is that advanced tasks are more steps than simple ones, not that everyone has to configure everything every time.

**Comment by dredstone1** [comment]
So why not removing the "show skip button" checkbox and let the user enable or disable the button or the auto skip in the client configuration.
And just keep the auto skip options for the client list and the user list in the future.

**Comment by AbandonedCart** [comment]
> So why not removing the "show skip button" checkbox and let the user enable or disable the button or the auto skip in the client configuration. And just keep the auto skip options for the client list and the user list in the future.

So rather than a simple checkbox for auto, each person that wants to enable auto universally should connect with each of those clients ahead of time and enable them individually. In addition, they will have to return every time a new client is added and add that, too?

I think what you are suggesting is literally the scenario we currently have that this PR aims to eliminate.

**Comment by dredstone1** [comment]
if you enable auto skip in the configuration it will force auto skip in the web client? even if the client option says otherwise?

**Comment by AbandonedCart** [comment]
Yes. That is why it says **all** clients.

**Comment by dredstone1** [comment]
OK so there is a problem on my testing jellyfin instence. When I test it before it wasnt auto skip, it just didn't show the button. I will do some more testing but if it's working for you, it's probably ok

**Comment by AbandonedCart** [comment]
If you don't enable either auto skip checkbox or the button checkbox, nothing happens.

If you only enable auto intro skip, the button text changes to credits and the client list only applies to credits. Intros auto skip for every client.

If you only enable auto credit skip, the button text changes to intros and the client list only applies to intros. Credits auto skip for every client.

If you enable both intro and credit auto skipping, the client list disappears because everything auto skips both intros and credits.

If you don't enable either auto and enable the button, the clients selected in the client list will automatically skip and anything not selected will display a button (assuming the client supports it).

**Comment by AbandonedCart** [comment]
Don't forget that if you messed with the settings in the player on the client, those override the server setting.

**Comment by dredstone1** [comment]
IL do some more testing later, but now it's look like it wount be very useful :)

**Comment by dredstone1** [comment]
i understand the confusion, it will be better to change the description from can be disabled, to, on web UI clients it will get override by the player configuration, or something like that.

**Comment by AbandonedCart** [comment]
> i understand the confusion, it will be better to change the description from can be disabled, to, on web UI clients it will get override by the player configuration, or something like that.

It reads “Individual clients can override this setting from the client player options.”

**Comment by AbandonedCart** [comment]
It was also added as a [note to the wiki](https://github.com/intro-skipper/intro-skipper/wiki/Settings-%E2%80%90-Playback) because it’s not specific to this PR.

**Comment by dredstone1** [comment]
OK I see that now, I still think that its not completely perfect but it can be improved over time. Also would it also be a good idea to hide the display skip button for the entire intro or something like that when the show skip button is disabled?

**Comment by AbandonedCart** [comment]
I don’t understand your request.

**Comment by dredstone1** [comment]
The display button for intro duration checkbox should hide when show skip intro button checkbox is not selected

**Comment by AbandonedCart** [comment]
Oh. I thought it was something related to what was changed.

**Comment by dredstone1** [comment]
No, but I saw that you changed the logic of this part of the configuration so I think it can be added in this pr

**Comment by AbandonedCart** [comment]
Sure. Let me finish with Android tv and then I can add it.

**Comment by AbandonedCart** [comment]
After looking at it, doing that wouldn’t make sense. If it disappears when the button is unchecked, but you select both skip options (hiding the previously checked button), then it wouldn’t be hidden.

**Comment by dredstone1** [comment]
OK I will add pr for that

**Comment by AbandonedCart** [comment]
I’ll handle it. It’s a lot bigger than just hiding the one checkbox. It’s all connected together.

**Comment by dredstone1** [comment]
OK. 
I know, you also would need to hide the other configuration that show up when it unselected. 
I can't wait to try the new apk file

**Comment by AbandonedCart** [comment]
Completed in https://github.com/intro-skipper/intro-skipper/pull/321

**Pull request merged**
