### PR TITLE
Handle in-season specials as part of the season

### PR DESCRIPTION
**Pull request by rlauuzo**
Requires the TVDB plugin to recognize in-season specials.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Can TheMovieDatabase identify the specials? That appears to come installed by default, whereas TVDB is an optional install.

**Comment by rlauuzo** [comment]
I believe only TVDB fills it automatically, but it also can be set in the metadata editor with options like 'Airs Before Season,' 'Airs After Season,' and so on.

**Comment by AbandonedCart** [comment]
https://www.themoviedb.org/talk/5cc6b4030e0a2633d0ee9991
 
Looks like TMDB does provide the TVDB ids, at least.

**Review by AbandonedCart — APPROVED** [review]

**Review by jumoog — APPROVED** [review]

**Comment by jumoog** [comment]
ready?

**Comment by rlauuzo** [comment]
Yes

**Pull request merged**
