### PR TITLE
implement 10.10 MediaSegments

### PR DESCRIPTION
**Pull request by jumoog**
No need to rush. It's ready when it's ready. PRs are always welcomed.

### CODE REVIEW

**Comment by ScottESanDiego** [comment]
Looks like @nielsvanvelzen is on the cusp of supporting segments in the Android TV client, so this would be very timely.

**Comment by AbandonedCart** [comment]
> Looks like @nielsvanvelzen is on the cusp of supporting segments in the Android TV client, so this would be very timely.

In he meantime, you are welcome to try out our [custom build](https://github.com/intro-skipper/jellyfin-androidtv/releases) that install alongside the official version.

**Comment by nielsvanvelzen** [comment]
@AbandonedCart please make the source of your fork available per the code license. The commit of the release in your "custom build" is dead.

**Comment by AbandonedCart** [comment]
> @AbandonedCart please make the source of your fork available per the code license. The commit of the release in your "custom build" is dead.

https://github.com/intro-skipper/jellyfin-androidtv

**Comment by nielsvanvelzen** [comment]
Like I said, the **commit of the release** which links to https://github.com/intro-skipper/jellyfin-androidtv/commit/da4ce28b66bead099df97a0cf6a46db3d14dceb7. You're putting up binary blobs that are not verifiable.

**Comment by AbandonedCart** [comment]
> Like I said, the **commit of the release** which links to [intro-skipper/jellyfin-androidtv@da4ce28](https://github.com/intro-skipper/jellyfin-androidtv/commit/da4ce28b66bead099df97a0cf6a46db3d14dceb7). You're putting up binary blobs that are not verifiable.

Actually, that's an inaccurate assumption. What happened is that the GitHub action modified the release binary, but not the release details due to an overlapping tag. A force push disconnected the hash listed from the hash of the actual commit.

I'm fixing the issue. Thanks for reporting it.

**Pull request closed without merging**
