### PR TITLE
add the option in the dashboard to select users to auto skip for

### PR DESCRIPTION
**Pull request by dredstone1**
this is using the user id so even when the user change his name it will not break everything.
when the auto skipper check if the client is selected it will also check if the user is select (it will need them to both to be selected)

From issue #126

### CODE REVIEW

**Comment by dredstone1** [comment]
Do you think that it should auto select every user by default or not auto select every user by default?

**Comment by AbandonedCart** [comment]
If you are going to do it per user, one user shouldn’t decide for another. Problem is that non-admin users shouldn’t be able to exceed the server setting.

**Comment by jumoog** [comment]
yeah only server admin change it

**Comment by AbandonedCart** [comment]
I misread the heading. I thought each user would have their own client settings. That’s a rabbit hole you don’t want to jump into.

**Comment by dredstone1** [comment]
OK, I know, it just adding a list similar to the device list.
Now it save a string containing all of the user IDs to auto skip to, is it better to save only the user ids to not auto skip to that mean that it will auto select the user to auto skip for

**Comment by dredstone1** [comment]
OK I know understand where is the misunderstanding in the heading.
😂

**Comment by jumoog** [comment]
will do some test tomorrow

**Comment by jumoog** [comment]
You should add a description and in my opinion it would be better to have a blacklist. You select the users to exclude from autoskip

**Comment by AbandonedCart** [comment]
I still don't see the use case for this. Like your uncle is coming to visit and you really hate that guy, so he has to watch all the intros?

**Comment by dredstone1** [comment]
I actually let my uncle use my jellyfin server and he asked me to stop the auto skip and I do want it to auto skip on the TV, so I need to turn it off, this is really important to me.



> You should add a description and in my opinion it would be better to have a blacklist. You select the users to exclude from autoskip

That is what I asked, now I think that it will be better to keep it as a list of users to auto skip for(it will be better in my opinion to make it similar to the device list) but make the saved string that contain the user's ID to behave like ignore list. This is my opinion, AbandonedCart what do you think will be better?

**Comment by AbandonedCart** [comment]
If this is going to actually work, it should work like parental controls. 

I agree with jumoog (I didn't tag you :P ) about making it more like a blacklist, not a full set of options, but the only other use case I can think of would honestly be kids. Basically, it's going to be for people you want to always skip or people that should never skip (make those brats watch the intro EVERY TIME!)

The people in this list should get a set option and disable the client side options.

**Comment by dredstone1** [comment]
OK so I will add description and I will make it so the users who are selected in the list will not auto skip.
Is that correct?
I don't know how parental controls works

**Comment by AbandonedCart** [comment]
Parental controls is a common feature to lock “child” accounts out of certain features. One example would be that they can’t make purchases.

in this case, it means that selecting a method for a user should lock them out of simply changing it on the client themselves.

**Comment by dredstone1** [comment]
i don't think that it is a good idea but it doesn't matter because it should be in a different pr because it will need to also take into consideration the device list or movies(when playing movie there is still those options) and more...

**Comment by AbandonedCart** [comment]
I don't really understand what you mean by that. So you are creating a list that sets a specific skip setting for a user that is essentially irrelevant?

**Comment by dredstone1** [comment]
no, it creates a list that work **almost the same** as the device list(if someone is selected it will not auto skip for him, or the opposite).
not all of the users who are using my jellyfin server want auto skip.

**Comment by AbandonedCart** [comment]
But they can override that with the client setting.

**Comment by dredstone1** [comment]
not if they are using android tv(like my brother and uncle) or kodi

**Comment by AbandonedCart** [comment]
So you fix one specific usage by breaking every other?

**Comment by dredstone1** [comment]
i'm adding a feature without breaking anything.

**Comment by AbandonedCart** [comment]
When I told you the issue, you did that thing where you dismiss it as not relevant to the PR. The gist of that being that we go back and clean up all the scenarios that stop working because of the one this PR provides.

**Comment by AbandonedCart** [comment]
The reason it seems like I give you a hard time about almost every PR is that you seem to miss the big picture in favor of how you will use the server. The per-client skip settings are completely isolated from the server settings. That means your setting is effectively useless as soon as anyone (even accidentally) changes the client setting. 

Maybe you trust your uncle not to do that, but can you be sure that every person in the world is exactly like your uncle?

 Kids, who are another valid usage scenario for this **notoriously** press random buttons. I can see it being only a matter of days for some parent to report they enabled this setting and it got turned off, so how do they prevent that. I doubt “be more like @dredstone1 ‘s uncle” is a good response.

**Comment by dredstone1** [comment]
i didnt dismiss it, i am sorry if i make it look like that.
i think that you didnt understand my point, this will add the option to add a list of users id and when it check if a device is selected to auto skip, it will also if the user is selected to auto skip for.
this will not override the same as the device list is not override anything.

you are making me a hard time and that is good, you care about this plugin, and i understand, that is way im not giving up.
my uncle using only the tv version so he doesn't have client settings.

this will perform a regular auto skip like always, and if the user is been selected and the device is being selected it will not auto skip( or the opposite)

i think that you didnt understand me, and this is my fault so i hope this will explain it better.

**Comment by dredstone1** [comment]
i just want to clarify:
"client type" is the device list or if the auto skip is on?
"user has a setting" is the user list?

**Comment by AbandonedCart** [comment]
Client type is the server’s auto skip by client setting.

Client (gear) is the client’s player setting accessed with the gear icon.

User setting is your PR.

**Comment by dredstone1** [comment]
its more like that:

So at the top you have the server default.

If the client type (server setting) is selected and the user is selected( or not selected), it will auto skip.

If the client type (server setting) is not auto or the user is not selected(the same), it will do nothing.

if the client support the options(android tv and kodi does not)(gear), it will do what in the options.

**Comment by dredstone1** [comment]
i think that i understand your point, you are saying that its too much settings while we can just use the client configuration, this is not an option because a lot of users are using android tv and kodi, i think that this is the only reason auto skip in dashboard is still exist.

**Comment by AbandonedCart** [comment]
So you have to select both the client and the user or nothing happens?

**Comment by dredstone1** [comment]
this pr sort of continue the device list

**Comment by AbandonedCart** [comment]
So in the example of your uncle, he would auto skip on Android TV, but nobody else would until they were selected? And he wouldn't skip on any other platform because it's not Android TV?

**Comment by dredstone1** [comment]
like i said i think that i will make it auto select users(i still not sure about that), and in my case it would auto skip for me and it won't auto skip for him(because reasons that i cant understand) it will still let him auto skip through the client configuration(gear) the same as the device list.

**Comment by AbandonedCart** [comment]
But say you add another person, they'll be stuck with no auto until you add them to the user list?

**Comment by dredstone1** [comment]
that is correct, that is what i wanted to talk about.
currently it work by saving all of the selected users, this approach have a problem, like you describe it will require manually enable and that can be a problem.

my idea is to keep the ui the same, but instead of it adding the users that been selected to the file it will add the users that havent been selected, and the same in the autoskip.cs, it will not auto skip if the user is been saved. so in other word this will auto select new user, is that sound good?
this is the question i asked earlier.

**Comment by AbandonedCart** [comment]
I think that's why our fearless leader suggested inverting it. Instead of adding everyone, you select exceptions. It may still end up a little confusing because instead of a hierarchy, it's multiple conditions.

I don't know what you'd call it to keep it separate, though. What makes the most sense would be when you enable auto for a client, you could select "exceptions" to it. I think where it gets confusing is having two sets of options that seem to do the same thing and both need to be set to do it.

**Comment by dredstone1** [comment]
i did that so it will still look the same as the device list so it will not be confusing, but under the hood it behave like it reverse.
if you think that this is still a bit confusing i will revert it.

**Comment by dredstone1** [comment]
i think that its very clear.

**Comment by dredstone1** [comment]
i did some checks, and its working and look good, i think it's ready

**Comment by dredstone1** [comment]
this is ready for a review. @AbandonedCart @rlauuzo

**Comment by AbandonedCart** [comment]
You generally don’t need to tag anyone unless it’s not obvious who was meant to read it. I’m still testing how much help vs hassle this will create. As I mentioned before, the biggest concern is how devices where skip doesn’t work are a bit intuitive, but needing to also factor in users can easily lose people.

**Comment by dredstone1** [comment]
Currently the device list is auto selecting new devices?

**Comment by AbandonedCart** [comment]
No. It’s actually the opposite.

**Comment by dredstone1** [comment]
OK in this case it can be a bit confusing, I will make the device list work in the same way as the user list, i also going to try make it so it will make the migration OK.

**Comment by dredstone1** [comment]
Now i saw your edit, and in that case wouldn't it be better if it will stay as it currently is?
the device list is not auto selected and the user list is auto selected, and I will modify the description to address it

**Comment by dredstone1** [comment]
I think that this should wait to #317, and then I will apply the changes to this pr to work with #317.

Or the opposite will be better?

**Comment by AbandonedCart** [comment]
I think applying this first would be messy. #317 is actually aimed at resolving the root of where this gets even more confusing. The premise is that nothing, a button, and auto should be simple. It should only get more complicated as you get more specific about how each client / user is handled.

**Comment by dredstone1** [comment]
I think that adding the option to exclude certain users from auto skip is necessary and was asked by jumoog and I also would find it very useful(very very useful).
The first option does sound better(adding your pull request #317 first) because your fix(I didn't completely understand it, I would dig more into it tomorrow) seems to change a lot in the client list and all of the auto skip configuration, It may be even better creating new pr for it, I will dig into it tomorrow.

**Comment by AbandonedCart** [comment]
It changes how it’s presented to the user more than it changes the process.

**Comment by dredstone1** [comment]
OK, I will try it tomorro.

**Comment by AbandonedCart** [comment]
No rush. I'm still running scenarios trying to break my logic.

**Comment by dredstone1** [comment]
I will just let my brother try it, he will break it.

**Comment by dredstone1** [comment]
im closing it, until #317 will get merge

**Pull request closed without merging**
