### PR TITLE
options: don't use type time

### PR DESCRIPTION
**Pull request by jumoog**
input type="time" can't be forced to 24h  AM/PM is wrong

### CODE REVIEW

**Comment by jumoog** [comment]
problem: pattern only works on desktop

**Comment by AbandonedCart** [comment]
Chrome ruined it for everyone...

**Comment by jumoog** [comment]
I thought the days of each browser making its own choices were over

**Comment by AbandonedCart** [comment]
Apparently not for Samsung. Another reason I use Firefox.

**Pull request merged**
